# Generated by Django 3.0.5 on 2021-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_auto_20210221_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='exit',
            field=models.CharField(default='exit', max_length=200),
        ),
    ]
