# Generated by Django 3.0.5 on 2021-03-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_rota_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='exit_de',
            field=models.CharField(default='exit', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='exit_en',
            field=models.CharField(default='exit', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='exit_ru',
            field=models.CharField(default='exit', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='exit_tr',
            field=models.CharField(default='exit', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='liman_de',
            field=models.TextField(default='Açılama Giriniz.', null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='liman_en',
            field=models.TextField(default='Açılama Giriniz.', null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='liman_ru',
            field=models.TextField(default='Açılama Giriniz.', null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='liman_tr',
            field=models.TextField(default='Açılama Giriniz.', null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='name_de',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='name_tr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='rota_de',
            field=models.CharField(default='Bölge', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='rota_en',
            field=models.CharField(default='Bölge', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='rota_ru',
            field=models.CharField(default='Bölge', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='rota_tr',
            field=models.CharField(default='Bölge', max_length=200, null=True),
        ),
    ]
