# Generated by Django 3.0.5 on 2021-02-13 10:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['-id'],
                'unique_together': {('slug', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Name', max_length=50)),
                ('phone', models.CharField(db_index=True, default='Phone', max_length=50)),
                ('email', models.CharField(db_index=True, default='Emil', max_length=50)),
                ('subject', models.CharField(db_index=True, default='subject', max_length=50)),
                ('text', models.CharField(db_index=True, default='Name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='İndexComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Name', max_length=50)),
                ('city', models.CharField(db_index=True, default='Phone', max_length=50)),
                ('subject', models.CharField(db_index=True, default='subject', max_length=50)),
                ('text', models.TextField(default='Ürün Aaçıklama 263 Ten az 263 çok olmuyacak', max_length=263)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('adult', models.CharField(db_index=True, max_length=200)),
                ('children', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(db_index=True, max_length=200)),
                ('telephone', models.CharField(db_index=True, max_length=200)),
                ('enter_date', models.CharField(db_index=True, max_length=200)),
                ('out_date', models.CharField(db_index=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('clone', models.CharField(db_index=True, max_length=200)),
                ('vitrin', models.CharField(db_index=True, default='Ürün Vitrin is : vitrin yaz', max_length=200)),
                ('imgseo', models.CharField(db_index=True, default='İmage Seo Alt Ekle', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image5', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image6', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image7', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image8', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image9', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image10', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image11', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image12', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image13', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image14', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image15', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image16', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image17', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image18', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image19', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image20', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('index_info', models.TextField(default='89 Karakter En fazla', max_length=89)),
                ('general_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_june', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_july', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_agust', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_sept', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_octo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meter', models.CharField(db_index=True, default='Gulet Meter', max_length=200)),
                ('person', models.CharField(db_index=True, default='Gulet Person', max_length=200)),
                ('shower', models.CharField(db_index=True, default='Gulet Shower', max_length=200)),
                ('kabin', models.CharField(db_index=True, default='Toplam Kabin Sayısı Giriniz.', max_length=200)),
                ('aircon', models.CharField(db_index=True, default='Var', max_length=200)),
                ('kabin_type', models.CharField(db_index=True, default='Gulet Double', max_length=200)),
                ('description', models.TextField(db_index=True, default='160 Kelime', max_length=200)),
                ('title', models.TextField(default='50-60 Kelime', max_length=500)),
                ('key', models.TextField(default='1 Kelime', max_length=550)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boats', to='rent.Category')),
            ],
            options={
                'ordering': ['-id'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
