# Generated by Django 3.0.5 on 2021-03-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_category_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image20',
        ),
    ]
