# Generated by Django 3.0.5 on 2021-03-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20210311_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='city',
        ),
    ]
