# Generated by Django 3.0.5 on 2021-03-13 17:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_remove_reservation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index_info_de',
            field=models.TextField(default='89 Karakter En fazla', max_length=89, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='index_info_en',
            field=models.TextField(default='89 Karakter En fazla', max_length=89, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='index_info_ru',
            field=models.TextField(default='89 Karakter En fazla', max_length=89, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='index_info_tr',
            field=models.TextField(default='89 Karakter En fazla', max_length=89, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
