# Generated by Django 3.0.5 on 2021-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20210313_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='city_de',
            field=models.CharField(db_index=True, default='Phone', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='city_en',
            field=models.CharField(db_index=True, default='Phone', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='city_ru',
            field=models.CharField(db_index=True, default='Phone', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='city_tr',
            field=models.CharField(db_index=True, default='Phone', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='name_de',
            field=models.CharField(db_index=True, default='Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='name_en',
            field=models.CharField(db_index=True, default='Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='name_ru',
            field=models.CharField(db_index=True, default='Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='name_tr',
            field=models.CharField(db_index=True, default='Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='subject_de',
            field=models.CharField(db_index=True, default='subject', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='subject_en',
            field=models.CharField(db_index=True, default='subject', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='subject_ru',
            field=models.CharField(db_index=True, default='subject', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='subject_tr',
            field=models.CharField(db_index=True, default='subject', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='text_de',
            field=models.TextField(default='Ürün Aaçıklama 263 Ten az 263 çok olmuyacak', max_length=263, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='text_en',
            field=models.TextField(default='Ürün Aaçıklama 263 Ten az 263 çok olmuyacak', max_length=263, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='text_ru',
            field=models.TextField(default='Ürün Aaçıklama 263 Ten az 263 çok olmuyacak', max_length=263, null=True),
        ),
        migrations.AddField(
            model_name='i̇ndexcomment',
            name='text_tr',
            field=models.TextField(default='Ürün Aaçıklama 263 Ten az 263 çok olmuyacak', max_length=263, null=True),
        ),
    ]
