# Generated by Django 3.0.5 on 2021-04-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image9',
        ),
    ]
