# Generated by Django 3.0.5 on 2021-02-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialcategory',
            options={'ordering': ['-id']},
        ),
    ]
