# Generated by Django 3.0.5 on 2021-03-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_auto_20210215_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialproducts',
            name='list_content',
        ),
    ]
