# Generated by Django 3.0.5 on 2021-03-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210215_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='smiler',
        ),
        migrations.RemoveField(
            model_name='post',
            name='strong_content',
        ),
    ]
