# Generated by Django 3.0.5 on 2021-02-13 11:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['-id'],
                'unique_together': {('slug', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('clone', models.CharField(db_index=True, max_length=200)),
                ('vitrin', models.CharField(db_index=True, default='Ürün Vitrin is : vitrin yaz', max_length=200)),
                ('imgseo', models.CharField(db_index=True, default='İmage Seo Alt Ekle', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image5', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image6', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image7', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image8', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image9', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image10', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image11', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image12', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image13', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image14', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image15', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image16', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image17', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image18', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image19', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image20', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('index_info', models.TextField(default='89 Karakter En fazla', max_length=89)),
                ('general_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(db_index=True, default='160 Kelime', max_length=200)),
                ('title', models.TextField(default='50-60 Kelime', max_length=500)),
                ('key', models.TextField(default='1 Kelime', max_length=550)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boats', to='sell.SellCategory')),
            ],
            options={
                'ordering': ['-id'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
