# Generated by Django 3.0.5 on 2021-02-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellcategory',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Sell Categories'},
        ),
    ]
