# Generated by Django 3.0.5 on 2021-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20210213_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='image18',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='image19',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='image20',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='boatHull',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='cabin',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='certificate',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='firstLaunch',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='flag',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='fuel',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='fuelCapacity',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='headroom',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='hp',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='length',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='metarialDeck',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='model',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='motorCompany',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='producer',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='sale',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='saleType',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='status',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='waterCapacity',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='wc',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='weight',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='year',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='clone',
            field=models.CharField(db_index=True, default='Example', max_length=200),
        ),
    ]
