# Generated by Django 3.0.5 on 2021-03-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_auto_20210218_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='aircon',
            field=models.CharField(db_index=True, default='Var', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='kabin',
            field=models.CharField(db_index=True, default='Toplam Kabin Sayısı Giriniz.', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='kabin_type',
            field=models.CharField(db_index=True, default='Gulet Double', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='meter',
            field=models.CharField(db_index=True, default='Gulet Meter', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='person',
            field=models.CharField(db_index=True, default='Gulet Person', max_length=200),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='shower',
            field=models.CharField(db_index=True, default='Gulet Shower', max_length=200),
        ),
    ]
