# Generated by Django 3.0.5 on 2021-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20210310_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.CharField(db_index=True, max_length=200)),
                ('telephone', models.CharField(db_index=True, max_length=200)),
                ('text', models.TextField(db_index=True, default='160 Kelime', max_length=200)),
            ],
        ),
    ]
