# Generated by Django 3.0.5 on 2021-03-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_salesship'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesship',
            name='product',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
    ]
